FROM alpine:latest  
RUN apk --no-cache add ca-certificates tzdata curl bash

# Install golang-migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate /usr/local/bin/migrate && \
    chmod +x /usr/local/bin/migrate

WORKDIR /app

# Copy the Pre-built binary files from the local bin-prod directory (built by 'make deploy')
COPY bin-prod/main .
COPY bin-prod/seed_idbi_customers .
COPY start.sh .
COPY internal/database/migrations ./migrations
COPY ["docs/IDBI APIs - Data.csv", "./docs/IDBI APIs - Data.csv"]

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
ENTRYPOINT ["/app/start.sh"]
