apiVersion: v1
kind: Secret
metadata:
  name: astra-api-secrets
  labels:
    app: astra-api
type: Opaque
stringData:
  # NOTE: The database URL is configured without a password. If a password is required later, add it as postgres:PASSWORD@...
  DATABASE_URL: "postgres://postgres:idbi-34f543%23%2A@abhimanyu-gupta-psql-rds.cxgiym4yu3kl.ap-south-1.rds.amazonaws.com:5432/abhimanyu_gupta_psql_rds?sslmode=verify-full&sslrootcert=/app/global-bundle.pem"
  JWT_SECRET: "E56kUTDPOcrPv/bXRoyX1QC9oiSSNI4m9r03Axqme0MSR9FioTIEq7HMWDoBWQCAkO36OjqUkVdN"
  RM_JWT_SECRET: "changeme-production-rm-jwt-secret"
  GROQ_API_KEY: "Lcqk4T33uylUWiYINZNmIVXCQAXBk5JtNSqdg6qL3z3+IF8XzaQN2GzuHtSc4tVPLQb/"
  SARVAM_API_KEY: "+5Vo88gniJl+J0JyBXB75HgXqak/m6bTxrwB4jlT5BfSXrir8Xm3rQKVWQn4FINmUDsxFnZUt+MoxhW0mfXm5Q=="

#export RDSHOST="abhimanyu-gupta-psql-rds.cxgiym4yu3kl.ap-south-1.rds.amazonaws.com"
#psql "host=$RDSHOST port=5432 dbname=abhimanyu_gupta_psql_rds user=postgres sslmode=verify-full sslrootcert=./global-bundle.pem"
