DELETE FROM fund_allocation WHERE scheme_code IN (
    'MOTILAL-NASDAQ100-G','FRANKLIN-USOPP-G','EDEL-EUROPE-G','ICICI-SILVER-G','KOTAK-REIT-G',
    'TATA-GREENENERGY-G','ICICI-TECH-G','MIRAE-SEMICON-G','ICICI-MANUF-G','MIRAE-EVMOB-G',
    'ICICI-AUTO-G','HDFC-CORPBOND-G','SBI-CONSHYBRID-G','AXIS-AGGRHYBRID-G'
);
DELETE FROM fund_catalog WHERE scheme_code IN (
    'MOTILAL-NASDAQ100-G','FRANKLIN-USOPP-G','EDEL-EUROPE-G','ICICI-SILVER-G','KOTAK-REIT-G',
    'TATA-GREENENERGY-G','ICICI-TECH-G','MIRAE-SEMICON-G','ICICI-MANUF-G','MIRAE-EVMOB-G',
    'ICICI-AUTO-G','HDFC-CORPBOND-G','SBI-CONSHYBRID-G','AXIS-AGGRHYBRID-G'
);
