UPDATE fund_catalog SET returns_1y = NULL, returns_5y = NULL
WHERE scheme_code IN (
    'MIRAE-LC-G','HDFC-T100-G','ICICI-BC-G','SBI-BLC-G','AXIS-BC-G',
    'QUANT-MC-G','NIPPON-GR-G','HDFC-MC-G','MOTILAL-MC-G','EDEL-MC-G',
    'NIPPON-SC-G','SBI-SC-G','AXIS-SC-G','DSP-SC-G','QUANT-SC-G',
    'PARAG-FLX-G',
    'QUANT-VAL-G','AXIS-VAL-G','HSBC-VAL-G','DSP-VAL-G','LIC-VAL-G','HDFC-VAL-G','ABSL-VAL-G',
    'ICICI-TECH-G','ICICI-MANUF-G','MIRAE-SEMI-G','SBI-HC-G','TATA-GREEN-G','MIRAE-EVMOB-G',
    'MOTILAL-N100-G','NIPPON-JP-G','INVESCO-EU-G',
    'HDFC-CORPBOND-G','SBI-STD-G','ICICI-LIQ-G','SBI-GILT-G','ICICI-TFB-G',
    'NIPPON-GOLD-G','ICICI-SILVER-G',
    'UTI-N50-G'
);

UPDATE fund_catalog SET returns_3y = NULL, returns_5y = NULL
WHERE scheme_code IN ('EMBASSY-REIT-G','NEXUS-REIT-G','POWERGRID-INVIT-G','IRB-INVIT-G','BAJAJ-FD-G');
