// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_aa_consents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsent = `-- name: CreateConsent :exec
INSERT INTO idbi_aa_consents (
    consent_handle, user_id, consent_id, status, party_id_type, party_id_value,
    vua, product_id, account_id, redirect_url, web_redirect_url, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now())
ON CONFLICT (consent_handle) DO UPDATE SET
    consent_id       = COALESCE(NULLIF(EXCLUDED.consent_id, ''), idbi_aa_consents.consent_id),
    status           = CASE WHEN idbi_aa_consents.status = 'PENDING'
                            THEN EXCLUDED.status ELSE idbi_aa_consents.status END,
    redirect_url     = COALESCE(NULLIF(EXCLUDED.redirect_url, ''), idbi_aa_consents.redirect_url),
    web_redirect_url = COALESCE(NULLIF(EXCLUDED.web_redirect_url, ''), idbi_aa_consents.web_redirect_url),
    updated_at       = now()
`

type CreateConsentParams struct {
	ConsentHandle  string    `json:"consent_handle"`
	UserID         uuid.UUID `json:"user_id"`
	ConsentID      string    `json:"consent_id"`
	Status         string    `json:"status"`
	PartyIDType    string    `json:"party_id_type"`
	PartyIDValue   string    `json:"party_id_value"`
	Vua            string    `json:"vua"`
	ProductID      string    `json:"product_id"`
	AccountID      string    `json:"account_id"`
	RedirectUrl    string    `json:"redirect_url"`
	WebRedirectUrl string    `json:"web_redirect_url"`
}

func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) error {
	_, err := q.db.Exec(ctx, createConsent,
		arg.ConsentHandle,
		arg.UserID,
		arg.ConsentID,
		arg.Status,
		arg.PartyIDType,
		arg.PartyIDValue,
		arg.Vua,
		arg.ProductID,
		arg.AccountID,
		arg.RedirectUrl,
		arg.WebRedirectUrl,
	)
	return err
}

const getConsent = `-- name: GetConsent :one
SELECT consent_handle, user_id, consent_id, status, party_id_type, party_id_value,
       vua, product_id, account_id, redirect_url, web_redirect_url,
       approved_at, expires_at, last_fetched_at, created_at, updated_at
FROM idbi_aa_consents
WHERE consent_handle = $1
`

func (q *Queries) GetConsent(ctx context.Context, consentHandle string) (IdbiAaConsent, error) {
	row := q.db.QueryRow(ctx, getConsent, consentHandle)
	var i IdbiAaConsent
	err := row.Scan(
		&i.ConsentHandle,
		&i.UserID,
		&i.ConsentID,
		&i.Status,
		&i.PartyIDType,
		&i.PartyIDValue,
		&i.Vua,
		&i.ProductID,
		&i.AccountID,
		&i.RedirectUrl,
		&i.WebRedirectUrl,
		&i.ApprovedAt,
		&i.ExpiresAt,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsentsByUser = `-- name: ListConsentsByUser :many
SELECT consent_handle, user_id, consent_id, status, party_id_type, party_id_value,
       vua, product_id, account_id, redirect_url, web_redirect_url,
       approved_at, expires_at, last_fetched_at, created_at, updated_at
FROM idbi_aa_consents
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConsentsByUser(ctx context.Context, userID uuid.UUID) ([]IdbiAaConsent, error) {
	rows, err := q.db.Query(ctx, listConsentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdbiAaConsent{}
	for rows.Next() {
		var i IdbiAaConsent
		if err := rows.Scan(
			&i.ConsentHandle,
			&i.UserID,
			&i.ConsentID,
			&i.Status,
			&i.PartyIDType,
			&i.PartyIDValue,
			&i.Vua,
			&i.ProductID,
			&i.AccountID,
			&i.RedirectUrl,
			&i.WebRedirectUrl,
			&i.ApprovedAt,
			&i.ExpiresAt,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConsentFetched = `-- name: MarkConsentFetched :exec
UPDATE idbi_aa_consents
SET last_fetched_at = now(), updated_at = now()
WHERE consent_handle = $1
`

func (q *Queries) MarkConsentFetched(ctx context.Context, consentHandle string) error {
	_, err := q.db.Exec(ctx, markConsentFetched, consentHandle)
	return err
}

const updateConsentStatus = `-- name: UpdateConsentStatus :execrows
UPDATE idbi_aa_consents SET
    status      = $2,
    consent_id  = COALESCE(NULLIF($3::text, ''), consent_id),
    approved_at = COALESCE($4, approved_at),
    updated_at  = now()
WHERE consent_handle = $1
`

type UpdateConsentStatusParams struct {
	ConsentHandle string             `json:"consent_handle"`
	Status        string             `json:"status"`
	Column3       string             `json:"column_3"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) UpdateConsentStatus(ctx context.Context, arg UpdateConsentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConsentStatus,
		arg.ConsentHandle,
		arg.Status,
		arg.Column3,
		arg.ApprovedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
