// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_spend.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSpendTransaction = `-- name: UpsertSpendTransaction :exec
INSERT INTO spend_transactions
    (user_id, amount, type, category, merchant, occurred_at, source, external_id, account_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, source, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    amount      = EXCLUDED.amount,
    type        = EXCLUDED.type,
    category    = EXCLUDED.category,
    merchant    = EXCLUDED.merchant,
    occurred_at = EXCLUDED.occurred_at,
    account_ref = EXCLUDED.account_ref
`

type UpsertSpendTransactionParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Type       string             `json:"type"`
	Category   string             `json:"category"`
	Merchant   string             `json:"merchant"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Source     string             `json:"source"`
	ExternalID pgtype.Text        `json:"external_id"`
	AccountRef pgtype.Text        `json:"account_ref"`
}

func (q *Queries) UpsertSpendTransaction(ctx context.Context, arg UpsertSpendTransactionParams) error {
	_, err := q.db.Exec(ctx, upsertSpendTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Merchant,
		arg.OccurredAt,
		arg.Source,
		arg.ExternalID,
		arg.AccountRef,
	)
	return err
}
