// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_aa_linked_accounts.sql

package db

import (
	"context"
)

const deleteAllLinkedAccounts = `-- name: DeleteAllLinkedAccounts :exec
DELETE FROM idbi_aa_linked_accounts WHERE consent_handle = $1
`

func (q *Queries) DeleteAllLinkedAccounts(ctx context.Context, consentHandle string) error {
	_, err := q.db.Exec(ctx, deleteAllLinkedAccounts, consentHandle)
	return err
}

const deleteLinkedAccountsExcept = `-- name: DeleteLinkedAccountsExcept :exec
DELETE FROM idbi_aa_linked_accounts
WHERE consent_handle = $1 AND link_ref_number <> ALL($2::text[])
`

type DeleteLinkedAccountsExceptParams struct {
	ConsentHandle string   `json:"consent_handle"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) DeleteLinkedAccountsExcept(ctx context.Context, arg DeleteLinkedAccountsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteLinkedAccountsExcept, arg.ConsentHandle, arg.Column2)
	return err
}

const listLinkedAccounts = `-- name: ListLinkedAccounts :many
SELECT consent_handle, link_ref_number, fip_id, fip_name,
       account_type, fi_type, masked_account_number, linked_at
FROM idbi_aa_linked_accounts
WHERE consent_handle = $1
ORDER BY link_ref_number
`

func (q *Queries) ListLinkedAccounts(ctx context.Context, consentHandle string) ([]IdbiAaLinkedAccount, error) {
	rows, err := q.db.Query(ctx, listLinkedAccounts, consentHandle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdbiAaLinkedAccount{}
	for rows.Next() {
		var i IdbiAaLinkedAccount
		if err := rows.Scan(
			&i.ConsentHandle,
			&i.LinkRefNumber,
			&i.FipID,
			&i.FipName,
			&i.AccountType,
			&i.FiType,
			&i.MaskedAccountNumber,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLinkedAccount = `-- name: UpsertLinkedAccount :exec
INSERT INTO idbi_aa_linked_accounts (
    consent_handle, link_ref_number, fip_id, fip_name,
    account_type, fi_type, masked_account_number, linked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (consent_handle, link_ref_number) DO UPDATE SET
    fip_id                = EXCLUDED.fip_id,
    fip_name              = EXCLUDED.fip_name,
    account_type          = EXCLUDED.account_type,
    fi_type               = EXCLUDED.fi_type,
    masked_account_number = EXCLUDED.masked_account_number
`

type UpsertLinkedAccountParams struct {
	ConsentHandle       string `json:"consent_handle"`
	LinkRefNumber       string `json:"link_ref_number"`
	FipID               string `json:"fip_id"`
	FipName             string `json:"fip_name"`
	AccountType         string `json:"account_type"`
	FiType              string `json:"fi_type"`
	MaskedAccountNumber string `json:"masked_account_number"`
}

func (q *Queries) UpsertLinkedAccount(ctx context.Context, arg UpsertLinkedAccountParams) error {
	_, err := q.db.Exec(ctx, upsertLinkedAccount,
		arg.ConsentHandle,
		arg.LinkRefNumber,
		arg.FipID,
		arg.FipName,
		arg.AccountType,
		arg.FiType,
		arg.MaskedAccountNumber,
	)
	return err
}
