// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_ckyc.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCKYC = `-- name: GetCKYC :one
SELECT id, user_id, pan, ckyc_available, ckyc_id, ckyc_name,
       ckyc_acc_type, ckyc_gen_date, id_types, verified_at
FROM idbi_ckyc
WHERE user_id = $1 AND pan = $2
`

type GetCKYCParams struct {
	UserID uuid.UUID `json:"user_id"`
	Pan    string    `json:"pan"`
}

func (q *Queries) GetCKYC(ctx context.Context, arg GetCKYCParams) (IdbiCkyc, error) {
	row := q.db.QueryRow(ctx, getCKYC, arg.UserID, arg.Pan)
	var i IdbiCkyc
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Pan,
		&i.CkycAvailable,
		&i.CkycID,
		&i.CkycName,
		&i.CkycAccType,
		&i.CkycGenDate,
		&i.IDTypes,
		&i.VerifiedAt,
	)
	return i, err
}

const listCKYCByUser = `-- name: ListCKYCByUser :many
SELECT id, user_id, pan, ckyc_available, ckyc_id, ckyc_name,
       ckyc_acc_type, ckyc_gen_date, id_types, verified_at
FROM idbi_ckyc
WHERE user_id = $1
ORDER BY verified_at DESC
`

func (q *Queries) ListCKYCByUser(ctx context.Context, userID uuid.UUID) ([]IdbiCkyc, error) {
	rows, err := q.db.Query(ctx, listCKYCByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdbiCkyc{}
	for rows.Next() {
		var i IdbiCkyc
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Pan,
			&i.CkycAvailable,
			&i.CkycID,
			&i.CkycName,
			&i.CkycAccType,
			&i.CkycGenDate,
			&i.IDTypes,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCKYC = `-- name: UpsertCKYC :exec
INSERT INTO idbi_ckyc (
    user_id, pan, ckyc_available, ckyc_id, ckyc_name,
    ckyc_acc_type, ckyc_gen_date, id_types, verified_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (user_id, pan) DO UPDATE SET
    ckyc_available = EXCLUDED.ckyc_available,
    ckyc_id        = EXCLUDED.ckyc_id,
    ckyc_name      = EXCLUDED.ckyc_name,
    ckyc_acc_type  = EXCLUDED.ckyc_acc_type,
    ckyc_gen_date  = EXCLUDED.ckyc_gen_date,
    id_types       = EXCLUDED.id_types,
    verified_at    = now()
`

type UpsertCKYCParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Pan           string    `json:"pan"`
	CkycAvailable bool      `json:"ckyc_available"`
	CkycID        string    `json:"ckyc_id"`
	CkycName      string    `json:"ckyc_name"`
	CkycAccType   string    `json:"ckyc_acc_type"`
	CkycGenDate   string    `json:"ckyc_gen_date"`
	IDTypes       []string  `json:"id_types"`
}

func (q *Queries) UpsertCKYC(ctx context.Context, arg UpsertCKYCParams) error {
	_, err := q.db.Exec(ctx, upsertCKYC,
		arg.UserID,
		arg.Pan,
		arg.CkycAvailable,
		arg.CkycID,
		arg.CkycName,
		arg.CkycAccType,
		arg.CkycGenDate,
		arg.IDTypes,
	)
	return err
}
