// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_customer_link.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCustomerLink = `-- name: DeleteCustomerLink :exec
DELETE FROM idbi_customer_link WHERE user_id = $1
`

func (q *Queries) DeleteCustomerLink(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomerLink, userID)
	return err
}

const getCustomerLink = `-- name: GetCustomerLink :one
SELECT user_id, cif_id, cust_id, source, linked_at, updated_at
FROM idbi_customer_link
WHERE user_id = $1
`

func (q *Queries) GetCustomerLink(ctx context.Context, userID uuid.UUID) (IdbiCustomerLink, error) {
	row := q.db.QueryRow(ctx, getCustomerLink, userID)
	var i IdbiCustomerLink
	err := row.Scan(
		&i.UserID,
		&i.CifID,
		&i.CustID,
		&i.Source,
		&i.LinkedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerLinkByCifID = `-- name: GetCustomerLinkByCifID :one
SELECT user_id, cif_id, cust_id, source, linked_at, updated_at
FROM idbi_customer_link
WHERE cif_id = $1
LIMIT 1
`

func (q *Queries) GetCustomerLinkByCifID(ctx context.Context, cifID string) (IdbiCustomerLink, error) {
	row := q.db.QueryRow(ctx, getCustomerLinkByCifID, cifID)
	var i IdbiCustomerLink
	err := row.Scan(
		&i.UserID,
		&i.CifID,
		&i.CustID,
		&i.Source,
		&i.LinkedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomerLink = `-- name: UpsertCustomerLink :exec
INSERT INTO idbi_customer_link (user_id, cif_id, cust_id, source, linked_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id) DO UPDATE SET
    cif_id     = EXCLUDED.cif_id,
    cust_id    = CASE WHEN EXCLUDED.cust_id <> '' THEN EXCLUDED.cust_id ELSE idbi_customer_link.cust_id END,
    source     = EXCLUDED.source,
    updated_at = now()
`

type UpsertCustomerLinkParams struct {
	UserID uuid.UUID `json:"user_id"`
	CifID  string    `json:"cif_id"`
	CustID string    `json:"cust_id"`
	Source string    `json:"source"`
}

func (q *Queries) UpsertCustomerLink(ctx context.Context, arg UpsertCustomerLinkParams) error {
	_, err := q.db.Exec(ctx, upsertCustomerLink,
		arg.UserID,
		arg.CifID,
		arg.CustID,
		arg.Source,
	)
	return err
}
