// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_seed_customers.sql

package db

import (
	"context"
)

const countSeedCustomers = `-- name: CountSeedCustomers :one
SELECT COUNT(*) FROM idbi_seed_customers
`

func (q *Queries) CountSeedCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSeedCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSeedCustomer = `-- name: GetSeedCustomer :one
SELECT cust_id, pan_number, customer_name, account_type, account_code, created_at, updated_at
FROM idbi_seed_customers
WHERE cust_id = $1
`

func (q *Queries) GetSeedCustomer(ctx context.Context, custID string) (IdbiSeedCustomer, error) {
	row := q.db.QueryRow(ctx, getSeedCustomer, custID)
	var i IdbiSeedCustomer
	err := row.Scan(
		&i.CustID,
		&i.PanNumber,
		&i.CustomerName,
		&i.AccountType,
		&i.AccountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeedCustomerByPAN = `-- name: GetSeedCustomerByPAN :one
SELECT cust_id, pan_number, customer_name, account_type, account_code, created_at, updated_at
FROM idbi_seed_customers
WHERE pan_number = $1
LIMIT 1
`

func (q *Queries) GetSeedCustomerByPAN(ctx context.Context, panNumber string) (IdbiSeedCustomer, error) {
	row := q.db.QueryRow(ctx, getSeedCustomerByPAN, panNumber)
	var i IdbiSeedCustomer
	err := row.Scan(
		&i.CustID,
		&i.PanNumber,
		&i.CustomerName,
		&i.AccountType,
		&i.AccountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSeedCustomers = `-- name: ListAllSeedCustomers :many
SELECT cust_id, pan_number, customer_name, account_type, account_code, created_at, updated_at
FROM idbi_seed_customers
ORDER BY account_type, cust_id
`

func (q *Queries) ListAllSeedCustomers(ctx context.Context) ([]IdbiSeedCustomer, error) {
	rows, err := q.db.Query(ctx, listAllSeedCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdbiSeedCustomer{}
	for rows.Next() {
		var i IdbiSeedCustomer
		if err := rows.Scan(
			&i.CustID,
			&i.PanNumber,
			&i.CustomerName,
			&i.AccountType,
			&i.AccountCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeedCustomersByAccountType = `-- name: ListSeedCustomersByAccountType :many
SELECT cust_id, pan_number, customer_name, account_type, account_code, created_at, updated_at
FROM idbi_seed_customers
WHERE account_type = $1
ORDER BY cust_id
`

func (q *Queries) ListSeedCustomersByAccountType(ctx context.Context, accountType string) ([]IdbiSeedCustomer, error) {
	rows, err := q.db.Query(ctx, listSeedCustomersByAccountType, accountType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdbiSeedCustomer{}
	for rows.Next() {
		var i IdbiSeedCustomer
		if err := rows.Scan(
			&i.CustID,
			&i.PanNumber,
			&i.CustomerName,
			&i.AccountType,
			&i.AccountCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSeedCustomer = `-- name: UpsertSeedCustomer :exec
INSERT INTO idbi_seed_customers (cust_id, pan_number, customer_name, account_type, account_code, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (cust_id) DO UPDATE SET
    pan_number    = EXCLUDED.pan_number,
    customer_name = EXCLUDED.customer_name,
    account_type  = EXCLUDED.account_type,
    account_code  = EXCLUDED.account_code,
    updated_at    = now()
`

type UpsertSeedCustomerParams struct {
	CustID       string `json:"cust_id"`
	PanNumber    string `json:"pan_number"`
	CustomerName string `json:"customer_name"`
	AccountType  string `json:"account_type"`
	AccountCode  string `json:"account_code"`
}

func (q *Queries) UpsertSeedCustomer(ctx context.Context, arg UpsertSeedCustomerParams) error {
	_, err := q.db.Exec(ctx, upsertSeedCustomer,
		arg.CustID,
		arg.PanNumber,
		arg.CustomerName,
		arg.AccountType,
		arg.AccountCode,
	)
	return err
}
