// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_credit_exposure.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCreditExposure = `-- name: GetCreditExposure :one
SELECT user_id, cif_id, customer_name, account_manager, cust_rating,
       total_limit, funded_limit, non_funded_limit, total_outstanding, utilisation_pct,
       loan_count, total_overdue, max_dpd, worst_npa_status, risk_band, synced_at
FROM idbi_credit_exposure
WHERE user_id = $1
`

func (q *Queries) GetCreditExposure(ctx context.Context, userID uuid.UUID) (IdbiCreditExposure, error) {
	row := q.db.QueryRow(ctx, getCreditExposure, userID)
	var i IdbiCreditExposure
	err := row.Scan(
		&i.UserID,
		&i.CifID,
		&i.CustomerName,
		&i.AccountManager,
		&i.CustRating,
		&i.TotalLimit,
		&i.FundedLimit,
		&i.NonFundedLimit,
		&i.TotalOutstanding,
		&i.UtilisationPct,
		&i.LoanCount,
		&i.TotalOverdue,
		&i.MaxDpd,
		&i.WorstNpaStatus,
		&i.RiskBand,
		&i.SyncedAt,
	)
	return i, err
}

const upsertCreditExposure = `-- name: UpsertCreditExposure :exec
INSERT INTO idbi_credit_exposure (
    user_id, cif_id, customer_name, account_manager, cust_rating,
    total_limit, funded_limit, non_funded_limit, total_outstanding, utilisation_pct,
    loan_count, total_overdue, max_dpd, worst_npa_status, risk_band, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now())
ON CONFLICT (user_id) DO UPDATE SET
    cif_id            = EXCLUDED.cif_id,
    customer_name     = EXCLUDED.customer_name,
    account_manager   = EXCLUDED.account_manager,
    cust_rating       = EXCLUDED.cust_rating,
    total_limit       = EXCLUDED.total_limit,
    funded_limit      = EXCLUDED.funded_limit,
    non_funded_limit  = EXCLUDED.non_funded_limit,
    total_outstanding = EXCLUDED.total_outstanding,
    utilisation_pct   = EXCLUDED.utilisation_pct,
    loan_count        = EXCLUDED.loan_count,
    total_overdue     = EXCLUDED.total_overdue,
    max_dpd           = EXCLUDED.max_dpd,
    worst_npa_status  = EXCLUDED.worst_npa_status,
    risk_band         = EXCLUDED.risk_band,
    synced_at         = now()
`

type UpsertCreditExposureParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	CifID            string         `json:"cif_id"`
	CustomerName     string         `json:"customer_name"`
	AccountManager   string         `json:"account_manager"`
	CustRating       string         `json:"cust_rating"`
	TotalLimit       pgtype.Numeric `json:"total_limit"`
	FundedLimit      pgtype.Numeric `json:"funded_limit"`
	NonFundedLimit   pgtype.Numeric `json:"non_funded_limit"`
	TotalOutstanding pgtype.Numeric `json:"total_outstanding"`
	UtilisationPct   pgtype.Numeric `json:"utilisation_pct"`
	LoanCount        int32          `json:"loan_count"`
	TotalOverdue     pgtype.Numeric `json:"total_overdue"`
	MaxDpd           int32          `json:"max_dpd"`
	WorstNpaStatus   string         `json:"worst_npa_status"`
	RiskBand         string         `json:"risk_band"`
}

func (q *Queries) UpsertCreditExposure(ctx context.Context, arg UpsertCreditExposureParams) error {
	_, err := q.db.Exec(ctx, upsertCreditExposure,
		arg.UserID,
		arg.CifID,
		arg.CustomerName,
		arg.AccountManager,
		arg.CustRating,
		arg.TotalLimit,
		arg.FundedLimit,
		arg.NonFundedLimit,
		arg.TotalOutstanding,
		arg.UtilisationPct,
		arg.LoanCount,
		arg.TotalOverdue,
		arg.MaxDpd,
		arg.WorstNpaStatus,
		arg.RiskBand,
	)
	return err
}
