// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_loans.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllLoans = `-- name: DeleteAllLoans :exec
DELETE FROM idbi_loans WHERE user_id = $1
`

func (q *Queries) DeleteAllLoans(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllLoans, userID)
	return err
}

const deleteLoansExcept = `-- name: DeleteLoansExcept :exec
DELETE FROM idbi_loans
WHERE user_id = $1 AND loan_account_id <> ALL($2::text[])
`

type DeleteLoansExceptParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 []string  `json:"column_2"`
}

func (q *Queries) DeleteLoansExcept(ctx context.Context, arg DeleteLoansExceptParams) error {
	_, err := q.db.Exec(ctx, deleteLoansExcept, arg.UserID, arg.Column2)
	return err
}

const getLoan = `-- name: GetLoan :one
SELECT loan_account_id, cust_id, holder_name,
       sanctioned_amount, disbursed_amount, available_amount, interest_rate,
       tenure_months, repayment_method, interest_method, opened_at,
       outstanding_balance, overdue_amount, dpd, npa_status, npa_date, synced_at
FROM idbi_loans
WHERE user_id = $1 AND loan_account_id = $2
`

type GetLoanParams struct {
	UserID        uuid.UUID `json:"user_id"`
	LoanAccountID string    `json:"loan_account_id"`
}

type GetLoanRow struct {
	LoanAccountID      string             `json:"loan_account_id"`
	CustID             string             `json:"cust_id"`
	HolderName         string             `json:"holder_name"`
	SanctionedAmount   pgtype.Numeric     `json:"sanctioned_amount"`
	DisbursedAmount    pgtype.Numeric     `json:"disbursed_amount"`
	AvailableAmount    pgtype.Numeric     `json:"available_amount"`
	InterestRate       pgtype.Numeric     `json:"interest_rate"`
	TenureMonths       int32              `json:"tenure_months"`
	RepaymentMethod    string             `json:"repayment_method"`
	InterestMethod     string             `json:"interest_method"`
	OpenedAt           pgtype.Timestamptz `json:"opened_at"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	OverdueAmount      pgtype.Numeric     `json:"overdue_amount"`
	Dpd                int32              `json:"dpd"`
	NpaStatus          string             `json:"npa_status"`
	NpaDate            pgtype.Timestamptz `json:"npa_date"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) GetLoan(ctx context.Context, arg GetLoanParams) (GetLoanRow, error) {
	row := q.db.QueryRow(ctx, getLoan, arg.UserID, arg.LoanAccountID)
	var i GetLoanRow
	err := row.Scan(
		&i.LoanAccountID,
		&i.CustID,
		&i.HolderName,
		&i.SanctionedAmount,
		&i.DisbursedAmount,
		&i.AvailableAmount,
		&i.InterestRate,
		&i.TenureMonths,
		&i.RepaymentMethod,
		&i.InterestMethod,
		&i.OpenedAt,
		&i.OutstandingBalance,
		&i.OverdueAmount,
		&i.Dpd,
		&i.NpaStatus,
		&i.NpaDate,
		&i.SyncedAt,
	)
	return i, err
}

const latestSpendSync = `-- name: LatestSpendSync :one
SELECT COALESCE(MAX(occurred_at), '1970-01-01 00:00:00+00'::timestamptz)::timestamptz AS latest_sync
FROM spend_transactions
WHERE user_id = $1 AND source = $2
`

type LatestSpendSyncParams struct {
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

func (q *Queries) LatestSpendSync(ctx context.Context, arg LatestSpendSyncParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestSpendSync, arg.UserID, arg.Source)
	var latest_sync pgtype.Timestamptz
	err := row.Scan(&latest_sync)
	return latest_sync, err
}

const listLoans = `-- name: ListLoans :many
SELECT loan_account_id, cust_id, holder_name,
       sanctioned_amount, disbursed_amount, available_amount, interest_rate,
       tenure_months, repayment_method, interest_method, opened_at,
       outstanding_balance, overdue_amount, dpd, npa_status, npa_date, synced_at
FROM idbi_loans
WHERE user_id = $1
ORDER BY loan_account_id
`

type ListLoansRow struct {
	LoanAccountID      string             `json:"loan_account_id"`
	CustID             string             `json:"cust_id"`
	HolderName         string             `json:"holder_name"`
	SanctionedAmount   pgtype.Numeric     `json:"sanctioned_amount"`
	DisbursedAmount    pgtype.Numeric     `json:"disbursed_amount"`
	AvailableAmount    pgtype.Numeric     `json:"available_amount"`
	InterestRate       pgtype.Numeric     `json:"interest_rate"`
	TenureMonths       int32              `json:"tenure_months"`
	RepaymentMethod    string             `json:"repayment_method"`
	InterestMethod     string             `json:"interest_method"`
	OpenedAt           pgtype.Timestamptz `json:"opened_at"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	OverdueAmount      pgtype.Numeric     `json:"overdue_amount"`
	Dpd                int32              `json:"dpd"`
	NpaStatus          string             `json:"npa_status"`
	NpaDate            pgtype.Timestamptz `json:"npa_date"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListLoans(ctx context.Context, userID uuid.UUID) ([]ListLoansRow, error) {
	rows, err := q.db.Query(ctx, listLoans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoansRow{}
	for rows.Next() {
		var i ListLoansRow
		if err := rows.Scan(
			&i.LoanAccountID,
			&i.CustID,
			&i.HolderName,
			&i.SanctionedAmount,
			&i.DisbursedAmount,
			&i.AvailableAmount,
			&i.InterestRate,
			&i.TenureMonths,
			&i.RepaymentMethod,
			&i.InterestMethod,
			&i.OpenedAt,
			&i.OutstandingBalance,
			&i.OverdueAmount,
			&i.Dpd,
			&i.NpaStatus,
			&i.NpaDate,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLoan = `-- name: UpsertLoan :exec
INSERT INTO idbi_loans (
    user_id, loan_account_id, cust_id, holder_name,
    sanctioned_amount, disbursed_amount, available_amount, interest_rate,
    tenure_months, repayment_method, interest_method, opened_at,
    outstanding_balance, overdue_amount, dpd, npa_status, npa_date, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, now())
ON CONFLICT (user_id, loan_account_id) DO UPDATE SET
    cust_id             = CASE WHEN EXCLUDED.cust_id <> '' THEN EXCLUDED.cust_id ELSE idbi_loans.cust_id END,
    holder_name         = CASE WHEN EXCLUDED.holder_name <> '' THEN EXCLUDED.holder_name ELSE idbi_loans.holder_name END,
    sanctioned_amount   = EXCLUDED.sanctioned_amount,
    disbursed_amount    = EXCLUDED.disbursed_amount,
    available_amount    = EXCLUDED.available_amount,
    interest_rate       = EXCLUDED.interest_rate,
    tenure_months       = EXCLUDED.tenure_months,
    repayment_method    = EXCLUDED.repayment_method,
    interest_method     = EXCLUDED.interest_method,
    opened_at           = COALESCE(EXCLUDED.opened_at, idbi_loans.opened_at),
    outstanding_balance = EXCLUDED.outstanding_balance,
    overdue_amount      = EXCLUDED.overdue_amount,
    dpd                 = EXCLUDED.dpd,
    npa_status          = EXCLUDED.npa_status,
    npa_date            = EXCLUDED.npa_date,
    synced_at           = now()
`

type UpsertLoanParams struct {
	UserID             uuid.UUID          `json:"user_id"`
	LoanAccountID      string             `json:"loan_account_id"`
	CustID             string             `json:"cust_id"`
	HolderName         string             `json:"holder_name"`
	SanctionedAmount   pgtype.Numeric     `json:"sanctioned_amount"`
	DisbursedAmount    pgtype.Numeric     `json:"disbursed_amount"`
	AvailableAmount    pgtype.Numeric     `json:"available_amount"`
	InterestRate       pgtype.Numeric     `json:"interest_rate"`
	TenureMonths       int32              `json:"tenure_months"`
	RepaymentMethod    string             `json:"repayment_method"`
	InterestMethod     string             `json:"interest_method"`
	OpenedAt           pgtype.Timestamptz `json:"opened_at"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	OverdueAmount      pgtype.Numeric     `json:"overdue_amount"`
	Dpd                int32              `json:"dpd"`
	NpaStatus          string             `json:"npa_status"`
	NpaDate            pgtype.Timestamptz `json:"npa_date"`
}

func (q *Queries) UpsertLoan(ctx context.Context, arg UpsertLoanParams) error {
	_, err := q.db.Exec(ctx, upsertLoan,
		arg.UserID,
		arg.LoanAccountID,
		arg.CustID,
		arg.HolderName,
		arg.SanctionedAmount,
		arg.DisbursedAmount,
		arg.AvailableAmount,
		arg.InterestRate,
		arg.TenureMonths,
		arg.RepaymentMethod,
		arg.InterestMethod,
		arg.OpenedAt,
		arg.OutstandingBalance,
		arg.OverdueAmount,
		arg.Dpd,
		arg.NpaStatus,
		arg.NpaDate,
	)
	return err
}
