// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idbi_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAccountsExcept = `-- name: DeleteAccountsExcept :exec
DELETE FROM idbi_accounts
WHERE user_id = $1 AND account_number <> ALL($2::text[])
`

type DeleteAccountsExceptParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 []string  `json:"column_2"`
}

func (q *Queries) DeleteAccountsExcept(ctx context.Context, arg DeleteAccountsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteAccountsExcept, arg.UserID, arg.Column2)
	return err
}

const deleteAllAccounts = `-- name: DeleteAllAccounts :exec
DELETE FROM idbi_accounts WHERE user_id = $1
`

func (q *Queries) DeleteAllAccounts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllAccounts, userID)
	return err
}

const getAccountByNumber = `-- name: GetAccountByNumber :one
SELECT account_number, account_type, currency, cif_id, cust_id,
       holder_name, status, branch_id, branch_name, opened_at,
       ledger_balance, available_balance, effective_balance, lien_amount, synced_at
FROM idbi_accounts
WHERE user_id = $1 AND account_number = $2
`

type GetAccountByNumberParams struct {
	UserID        uuid.UUID `json:"user_id"`
	AccountNumber string    `json:"account_number"`
}

type GetAccountByNumberRow struct {
	AccountNumber    string             `json:"account_number"`
	AccountType      string             `json:"account_type"`
	Currency         string             `json:"currency"`
	CifID            string             `json:"cif_id"`
	CustID           string             `json:"cust_id"`
	HolderName       string             `json:"holder_name"`
	Status           string             `json:"status"`
	BranchID         string             `json:"branch_id"`
	BranchName       string             `json:"branch_name"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	LedgerBalance    pgtype.Numeric     `json:"ledger_balance"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	EffectiveBalance pgtype.Numeric     `json:"effective_balance"`
	LienAmount       pgtype.Numeric     `json:"lien_amount"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) GetAccountByNumber(ctx context.Context, arg GetAccountByNumberParams) (GetAccountByNumberRow, error) {
	row := q.db.QueryRow(ctx, getAccountByNumber, arg.UserID, arg.AccountNumber)
	var i GetAccountByNumberRow
	err := row.Scan(
		&i.AccountNumber,
		&i.AccountType,
		&i.Currency,
		&i.CifID,
		&i.CustID,
		&i.HolderName,
		&i.Status,
		&i.BranchID,
		&i.BranchName,
		&i.OpenedAt,
		&i.LedgerBalance,
		&i.AvailableBalance,
		&i.EffectiveBalance,
		&i.LienAmount,
		&i.SyncedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT account_number, account_type, currency, cif_id, cust_id,
       holder_name, status, branch_id, branch_name, opened_at,
       ledger_balance, available_balance, effective_balance, lien_amount, synced_at
FROM idbi_accounts
WHERE user_id = $1
ORDER BY account_type, account_number
`

type ListAccountsRow struct {
	AccountNumber    string             `json:"account_number"`
	AccountType      string             `json:"account_type"`
	Currency         string             `json:"currency"`
	CifID            string             `json:"cif_id"`
	CustID           string             `json:"cust_id"`
	HolderName       string             `json:"holder_name"`
	Status           string             `json:"status"`
	BranchID         string             `json:"branch_id"`
	BranchName       string             `json:"branch_name"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	LedgerBalance    pgtype.Numeric     `json:"ledger_balance"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	EffectiveBalance pgtype.Numeric     `json:"effective_balance"`
	LienAmount       pgtype.Numeric     `json:"lien_amount"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.AccountNumber,
			&i.AccountType,
			&i.Currency,
			&i.CifID,
			&i.CustID,
			&i.HolderName,
			&i.Status,
			&i.BranchID,
			&i.BranchName,
			&i.OpenedAt,
			&i.LedgerBalance,
			&i.AvailableBalance,
			&i.EffectiveBalance,
			&i.LienAmount,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO idbi_accounts (
    user_id, account_number, account_type, currency, cif_id, cust_id,
    holder_name, status, branch_id, branch_name, opened_at,
    ledger_balance, available_balance, effective_balance, lien_amount, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now())
ON CONFLICT (user_id, account_number) DO UPDATE SET
    account_type      = EXCLUDED.account_type,
    currency          = EXCLUDED.currency,
    cif_id            = CASE WHEN EXCLUDED.cif_id <> '' THEN EXCLUDED.cif_id ELSE idbi_accounts.cif_id END,
    cust_id           = CASE WHEN EXCLUDED.cust_id <> '' THEN EXCLUDED.cust_id ELSE idbi_accounts.cust_id END,
    holder_name       = CASE WHEN EXCLUDED.holder_name <> '' THEN EXCLUDED.holder_name ELSE idbi_accounts.holder_name END,
    status            = EXCLUDED.status,
    branch_id         = CASE WHEN EXCLUDED.branch_id <> '' THEN EXCLUDED.branch_id ELSE idbi_accounts.branch_id END,
    branch_name       = CASE WHEN EXCLUDED.branch_name <> '' THEN EXCLUDED.branch_name ELSE idbi_accounts.branch_name END,
    opened_at         = COALESCE(EXCLUDED.opened_at, idbi_accounts.opened_at),
    ledger_balance    = EXCLUDED.ledger_balance,
    available_balance = EXCLUDED.available_balance,
    effective_balance = EXCLUDED.effective_balance,
    lien_amount       = EXCLUDED.lien_amount,
    synced_at         = now()
`

type UpsertAccountParams struct {
	UserID           uuid.UUID          `json:"user_id"`
	AccountNumber    string             `json:"account_number"`
	AccountType      string             `json:"account_type"`
	Currency         string             `json:"currency"`
	CifID            string             `json:"cif_id"`
	CustID           string             `json:"cust_id"`
	HolderName       string             `json:"holder_name"`
	Status           string             `json:"status"`
	BranchID         string             `json:"branch_id"`
	BranchName       string             `json:"branch_name"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	LedgerBalance    pgtype.Numeric     `json:"ledger_balance"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	EffectiveBalance pgtype.Numeric     `json:"effective_balance"`
	LienAmount       pgtype.Numeric     `json:"lien_amount"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount,
		arg.UserID,
		arg.AccountNumber,
		arg.AccountType,
		arg.Currency,
		arg.CifID,
		arg.CustID,
		arg.HolderName,
		arg.Status,
		arg.BranchID,
		arg.BranchName,
		arg.OpenedAt,
		arg.LedgerBalance,
		arg.AvailableBalance,
		arg.EffectiveBalance,
		arg.LienAmount,
	)
	return err
}
