// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	BankName    string             `json:"bank_name"`
	AccountType string             `json:"account_type"`
	Balance     pgtype.Numeric     `json:"balance"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Messages  []byte             `json:"messages"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IdbiAaConsent struct {
	ConsentHandle  string             `json:"consent_handle"`
	UserID         uuid.UUID          `json:"user_id"`
	ConsentID      string             `json:"consent_id"`
	Status         string             `json:"status"`
	PartyIDType    string             `json:"party_id_type"`
	PartyIDValue   string             `json:"party_id_value"`
	Vua            string             `json:"vua"`
	ProductID      string             `json:"product_id"`
	AccountID      string             `json:"account_id"`
	RedirectUrl    string             `json:"redirect_url"`
	WebRedirectUrl string             `json:"web_redirect_url"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastFetchedAt  pgtype.Timestamptz `json:"last_fetched_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type IdbiAaLinkedAccount struct {
	ConsentHandle       string             `json:"consent_handle"`
	LinkRefNumber       string             `json:"link_ref_number"`
	FipID               string             `json:"fip_id"`
	FipName             string             `json:"fip_name"`
	AccountType         string             `json:"account_type"`
	FiType              string             `json:"fi_type"`
	MaskedAccountNumber string             `json:"masked_account_number"`
	LinkedAt            pgtype.Timestamptz `json:"linked_at"`
}

type IdbiAccount struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	AccountNumber    string             `json:"account_number"`
	AccountType      string             `json:"account_type"`
	Currency         string             `json:"currency"`
	CifID            string             `json:"cif_id"`
	CustID           string             `json:"cust_id"`
	HolderName       string             `json:"holder_name"`
	Status           string             `json:"status"`
	BranchID         string             `json:"branch_id"`
	BranchName       string             `json:"branch_name"`
	OpenedAt         pgtype.Timestamptz `json:"opened_at"`
	LedgerBalance    pgtype.Numeric     `json:"ledger_balance"`
	AvailableBalance pgtype.Numeric     `json:"available_balance"`
	EffectiveBalance pgtype.Numeric     `json:"effective_balance"`
	LienAmount       pgtype.Numeric     `json:"lien_amount"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type IdbiCkyc struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Pan           string             `json:"pan"`
	CkycAvailable bool               `json:"ckyc_available"`
	CkycID        string             `json:"ckyc_id"`
	CkycName      string             `json:"ckyc_name"`
	CkycAccType   string             `json:"ckyc_acc_type"`
	CkycGenDate   string             `json:"ckyc_gen_date"`
	IDTypes       []string           `json:"id_types"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
}

type IdbiCreditExposure struct {
	UserID           uuid.UUID          `json:"user_id"`
	CifID            string             `json:"cif_id"`
	CustomerName     string             `json:"customer_name"`
	AccountManager   string             `json:"account_manager"`
	CustRating       string             `json:"cust_rating"`
	TotalLimit       pgtype.Numeric     `json:"total_limit"`
	FundedLimit      pgtype.Numeric     `json:"funded_limit"`
	NonFundedLimit   pgtype.Numeric     `json:"non_funded_limit"`
	TotalOutstanding pgtype.Numeric     `json:"total_outstanding"`
	UtilisationPct   pgtype.Numeric     `json:"utilisation_pct"`
	LoanCount        int32              `json:"loan_count"`
	TotalOverdue     pgtype.Numeric     `json:"total_overdue"`
	MaxDpd           int32              `json:"max_dpd"`
	WorstNpaStatus   string             `json:"worst_npa_status"`
	RiskBand         string             `json:"risk_band"`
	SyncedAt         pgtype.Timestamptz `json:"synced_at"`
}

type IdbiCustomerLink struct {
	UserID    uuid.UUID          `json:"user_id"`
	CifID     string             `json:"cif_id"`
	CustID    string             `json:"cust_id"`
	Source    string             `json:"source"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IdbiLoan struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	LoanAccountID      string             `json:"loan_account_id"`
	CustID             string             `json:"cust_id"`
	HolderName         string             `json:"holder_name"`
	SanctionedAmount   pgtype.Numeric     `json:"sanctioned_amount"`
	DisbursedAmount    pgtype.Numeric     `json:"disbursed_amount"`
	AvailableAmount    pgtype.Numeric     `json:"available_amount"`
	InterestRate       pgtype.Numeric     `json:"interest_rate"`
	TenureMonths       int32              `json:"tenure_months"`
	RepaymentMethod    string             `json:"repayment_method"`
	InterestMethod     string             `json:"interest_method"`
	OpenedAt           pgtype.Timestamptz `json:"opened_at"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	OverdueAmount      pgtype.Numeric     `json:"overdue_amount"`
	Dpd                int32              `json:"dpd"`
	NpaStatus          string             `json:"npa_status"`
	NpaDate            pgtype.Timestamptz `json:"npa_date"`
	SyncedAt           pgtype.Timestamptz `json:"synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type IdbiSeedCustomer struct {
	CustID       string             `json:"cust_id"`
	PanNumber    string             `json:"pan_number"`
	CustomerName string             `json:"customer_name"`
	AccountType  string             `json:"account_type"`
	AccountCode  string             `json:"account_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SpendTransaction struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Type       string             `json:"type"`
	Category   string             `json:"category"`
	Merchant   string             `json:"merchant"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Source     string             `json:"source"`
	ExternalID pgtype.Text        `json:"external_id"`
	AccountRef pgtype.Text        `json:"account_ref"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	AstraUserID string             `json:"astra_user_id"`
	Name        pgtype.Text        `json:"name"`
	PhoneNumber string             `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
